theme: jekyll-theme-minimal
title: "CODAI: COuntering Disinformation with Artificial Intelligence"
description: "Workshop on COuntering Disinformation with Artificial Intelligence"
show_downloads: false

